In [1]:
import pandas as pd
data = pd.read_csv('dataset.csv')
data_original = data.copy()
data.head(10)

,name_list,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,"จอมพล, กรุงเทพ","฿3,140,000",สร้างเสร็จในปี 2019,32,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,"สามเสนนอก, กรุงเทพ","฿5,850,000",ตู้เย็นเตาไฟฟ้าทีวี,8,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,"สุขุมวิท, กรุงเทพ","฿14,500,000",สร้างเสร็จในปี 2021,30,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,"สีลม, กรุงเทพ","฿15,000,000",สร้างเสร็จในปี 2022,15,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,"จอมพล, กรุงเทพ","฿6,347,000",สร้างเสร็จในปี 2021,11,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."
5,คอนโด Xt Ekkamai 2 นอน ชั้นสูง ใกล้ BTS ทองหล่อ,"สุขุมวิท, กรุงเทพ","฿8,290,000",สร้างเสร็จในปี 2020,23,2 ห้องนอน,2 ห้องน้ำ,46.5 ม.2,1430 ม. จาก BTS ทองหล่อ,"['สระว่ายน้ำ', 'ระบบรักษาความปลอดภัย 24 ชม.', ..."
6,ไลฟ์ สุขุมวิท 48,"พระโขนงใต้, กรุงเทพ","฿5,260,000",สร้างเสร็จในปี 2017,16,1 ห้องนอน,1 ห้องน้ำ,39.35 ม.2,530 ม. จาก BTS พระโขนง,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ร..."
7,บีทนิค สุขุมวิท 32,"พร้อมพงษ์, กรุงเทพ","฿19,000,000",สร้างเสร็จในปี 2018ไมโครเวฟห้องครัวพร้อมเตาอบทีวี,18,1 ห้องนอน,1 ห้องน้ำ,54.41 ม.2,370 ม. จาก BTS ทองหล่อ,"['สระว่ายน้ำ', 'เซาว์น่า', 'สวน', 'เตาบาร์บีคิ..."
8,เอ็ม จตุจักร,"จอมพล, กรุงเทพ","฿4,190,000",สร้างเสร็จในปี 2015ตู้เย็นไมโครเวฟเตาไฟฟ้าระเบ...,26,1 ห้องนอน,1 ห้องน้ำ,32.9 ม.2,450 ม. จาก BTS สะพานควาย,"['สระว่ายน้ำ', 'เซาว์น่า', 'สวน', 'สนามเด็กเล่..."
9,เวรี่ สุขุมวิท 72,สมุทรปราการ,"฿3,196,000",สร้างเสร็จในปี 2014ตู้เย็นไมโครเวฟระเบียงทีวี,4,2 ห้องนอน,2 ห้องน้ำ,52 ม.2,520 ม. จาก BTS แบริ่ง,"['สระว่ายน้ำ', 'สวน', 'กล้องวงจรปิด', 'ระบบรัก..."

## Built Year

In [2]:
import re
int(re.findall(r'\d+', data['built_year_list'][0])[0])

2019

In [3]:
built_year_list = []
for year in data['built_year_list']:
    try:
        built_year_list.append(int(re.findall(r'\d+', year)[0]))
    except:
        built_year_list.append(None)

built_year_list[:5]

[2019, None, 2021, 2022, 2021]

In [4]:
data['built_year_list'] = built_year_list
data.head(10)

,name_list,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,"จอมพล, กรุงเทพ","฿3,140,000",2019.0,32,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,"สามเสนนอก, กรุงเทพ","฿5,850,000",NaN,8,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,"สุขุมวิท, กรุงเทพ","฿14,500,000",2021.0,30,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,"สีลม, กรุงเทพ","฿15,000,000",2022.0,15,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,"จอมพล, กรุงเทพ","฿6,347,000",2021.0,11,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."
5,คอนโด Xt Ekkamai 2 นอน ชั้นสูง ใกล้ BTS ทองหล่อ,"สุขุมวิท, กรุงเทพ","฿8,290,000",2020.0,23,2 ห้องนอน,2 ห้องน้ำ,46.5 ม.2,1430 ม. จาก BTS ทองหล่อ,"['สระว่ายน้ำ', 'ระบบรักษาความปลอดภัย 24 ชม.', ..."
6,ไลฟ์ สุขุมวิท 48,"พระโขนงใต้, กรุงเทพ","฿5,260,000",2017.0,16,1 ห้องนอน,1 ห้องน้ำ,39.35 ม.2,530 ม. จาก BTS พระโขนง,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ร..."
7,บีทนิค สุขุมวิท 32,"พร้อมพงษ์, กรุงเทพ","฿19,000,000",2018.0,18,1 ห้องนอน,1 ห้องน้ำ,54.41 ม.2,370 ม. จาก BTS ทองหล่อ,"['สระว่ายน้ำ', 'เซาว์น่า', 'สวน', 'เตาบาร์บีคิ..."
8,เอ็ม จตุจักร,"จอมพล, กรุงเทพ","฿4,190,000",2015.0,26,1 ห้องนอน,1 ห้องน้ำ,32.9 ม.2,450 ม. จาก BTS สะพานควาย,"['สระว่ายน้ำ', 'เซาว์น่า', 'สวน', 'สนามเด็กเล่..."
9,เวรี่ สุขุมวิท 72,สมุทรปราการ,"฿3,196,000",2014.0,4,2 ห้องนอน,2 ห้องน้ำ,52 ม.2,520 ม. จาก BTS แบริ่ง,"['สระว่ายน้ำ', 'สวน', 'กล้องวงจรปิด', 'ระบบรัก..."

## Location

In [5]:
data['location_list'][0].split(', ')

['จอมพล', 'กรุงเทพ']

In [6]:
province = []
sub_area = []
for location in data['location_list']:
    try:
        province.append(location.split(', ')[1])
        sub_area.append(location.split(', ')[0])
    except:
        sub_area.append(None)
        province.append(location)

print(province[:5])
print(sub_area[:5])

['กรุงเทพ', 'กรุงเทพ', 'กรุงเทพ', 'กรุงเทพ', 'กรุงเทพ']
['จอมพล', 'สามเสนนอก', 'สุขุมวิท', 'สีลม', 'จอมพล']

In [7]:
data.insert(1, "Province", province)
data.insert(2, "Sub_Area", sub_area)
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿3,140,000",2019.0,32,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ","฿5,850,000",NaN,8,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ","฿14,500,000",2021.0,30,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ","฿15,000,000",2022.0,15,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿6,347,000",2021.0,11,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [8]:
data['Province'].value_counts()

กรุงเทพ            2507
ภูเก็ต               45
สมุทรปราการ          36
นนทบุรี              33
ประจวบคีรีขันธ์       6
ปทุมธานี              5
Name: Province, dtype: int64

In [9]:
data[data['Province'] == 'กรุงเทพ']

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿3,140,000",2019.0,32,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ","฿5,850,000",NaN,8,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ","฿14,500,000",2021.0,30,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ","฿15,000,000",2022.0,15,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿6,347,000",2021.0,11,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2627,ทาวเวอร์ พาร์ค,กรุงเทพ,นานา,"นานา, กรุงเทพ","฿35,200,000",1993.0,12,2 ห้องนอน,2 ห้องน้ำ,275 ม.2,740 ม. จาก ARL มักกะสัน,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ก..."
2628,บ้านสิริ สาทร เย็นอากาศ คอนโดมิเนียม,กรุงเทพ,ทุ่งมหาเมฆ,"ทุ่งมหาเมฆ, กรุงเทพ","฿9,900,000",2014.0,4,2 ห้องนอน,2 ห้องน้ำ,73 ม.2,910 ม. จาก MRT คลองเตย,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2629,เดอะ ลอฟท์ สีลม,กรุงเทพ,สุรศักดิ์,"สุรศักดิ์, กรุงเทพ","฿15,000,000",2020.0,15,2 ห้องนอน,2 ห้องน้ำ,54 ม.2,440 ม. จาก BTS สุรศักดิ์,"['เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องว..."
2630,เดอะ เม็ท สาทร,กรุงเทพ,ทุ่งมหาเมฆ,"ทุ่งมหาเมฆ, กรุงเทพ","฿119,000,000",2009.0,33,4 ห้องนอน,5 ห้องน้ำ,548 ม.2,540 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
2631,185 ราชดำริ,กรุงเทพ,ราชดําริ,"ราชดําริ, กรุงเทพ","฿100,000,000",2014.0,28,3 ห้องนอน,3 ห้องน้ำ,199 ม.2,420 ม. จาก BTS ราชดำริ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ก..."

In [10]:
floor_list = []
for floor in data['floor_list']:
    if type(floor) != float:
        if floor == '12A':
            floor = '12'
        elif floor == '12a':
            floor = '12'
        elif floor == 'G':
            floor = '1'
        elif floor == '11-20':
            floor = '15'
        elif floor == 'ุุุ6':
            floor = '6'
        elif floor == '5-10':
            floor = '7'
        elif floor == '\u200b26' or floor == '1970-01-01T00:00:00.007Z' or floor == '\u200b4':
            floor_list.append(None)
            continue
        elif floor == '17TH':
            floor = '17'
        elif floor == '10B':
            floor = '10'
        elif floor == '17-18':
            floor = '17'
        elif floor == '21-50':
            floor = '35'
        elif floor == '33-34':
            floor = '33'
        floor_list.append(int(floor))
    else:
        floor_list.append(None)
        
data['floor_list'] = floor_list
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿3,140,000",2019.0,32.0,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ","฿5,850,000",NaN,8.0,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ","฿14,500,000",2021.0,30.0,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ","฿15,000,000",2022.0,15.0,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿6,347,000",2021.0,11.0,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [11]:
from collections import Counter
Counter(floor_list)

Counter({32: 14,
         8: 288,
         30: 25,
         15: 87,
         11: 91,
         23: 47,
         16: 88,
         18: 103,
         26: 38,
         4: 185,
         5: 102,
         39: 17,
         3: 87,
         None: 29,
         9: 69,
         2: 71,
         14: 93,
         24: 48,
         19: 70,
         27: 35,
         22: 48,
         6: 114,
         10: 95,
         25: 43,
         7: 119,
         20: 111,
         12: 122,
         33: 20,
         31: 16,
         29: 25,
         36: 9,
         17: 87,
         21: 59,
         47: 3,
         1: 27,
         37: 10,
         28: 33,
         50: 10,
         38: 8,
         40: 5,
         13: 30,
         34: 9,
         55: 2,
         41: 9,
         35: 14,
         49: 1,
         42: 4,
         43: 2,
         45: 1,
         63: 2,
         46: 2,
         44: 1,
         66: 1,
         70: 1,
         68: 1,
         48: 1})

In [12]:
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿3,140,000",2019.0,32.0,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ","฿5,850,000",NaN,8.0,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ","฿14,500,000",2021.0,30.0,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ","฿15,000,000",2022.0,15.0,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ","฿6,347,000",2021.0,11.0,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [13]:
data['price_list'] = [int(price[1:].replace(',','')) for price in data['price_list']]
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",3140000,2019.0,32.0,1 ห้องนอน,1 ห้องน้ำ,23.53 ม.2,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ",5850000,NaN,8.0,1 ห้องนอน,1 ห้องน้ำ,66 ม.2,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ",14500000,2021.0,30.0,2 ห้องนอน,2 ห้องน้ำ,51.66 ม.2,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ",15000000,2022.0,15.0,1 ห้องนอน,1 ห้องน้ำ,45.77 ม.2,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",6347000,2021.0,11.0,1 ห้องนอน,1 ห้องน้ำ,35.09 ม.2,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [14]:
data['bedroom_list'] = [int(bedroom.split(' ')[0]) for bedroom in data['bedroom_list']]
data['bathroom_list'] = [int(bathroom.split(' ')[0]) for bathroom in data['bathroom_list']]
data['area_list'] = [float(area.split(' ')[0]) for area in data['area_list']]
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",3140000,2019.0,32.0,1,1,23.53,450 ม. จาก Saphan Khwai,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ",5850000,NaN,8.0,1,1,66.00,960 ม. จาก MRT ห้วยขวาง,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ",14500000,2021.0,30.0,2,2,51.66,1070 ม. จาก BTS ทองหล่อ,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ",15000000,2022.0,15.0,1,1,45.77,490 ม. จาก BTS ช่องนนทรี,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",6347000,2021.0,11.0,1,1,35.09,180 ม. จาก BTS ห้าแยกลาดพร้าว,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [15]:
distance_to_transport_list = []
for distance in data['distance_to_transport_list']:
    try:
        distance_to_transport_list.append(int(distance.split(' ')[0]))
    except:
        distance_to_transport_list.append(None)
        
distance_to_transport_list[:5]

[450, 960, 1070, 490, 180]

In [16]:
data['distance_to_transport_list'] = distance_to_transport_list
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",3140000,2019.0,32.0,1,1,23.53,450.0,"['สระว่ายน้ำ', 'ลานจอดรถ', 'กล้องวงจรปิด', 'สว..."
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ",5850000,NaN,8.0,1,1,66.00,960.0,"['ระบบรักษาความปลอดภัย 24 ชม.</li></ul>', '<ul..."
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ",14500000,2021.0,30.0,2,2,51.66,1070.0,"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟ..."
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ",15000000,2022.0,15.0,1,1,45.77,490.0,"['ห้องสมุด', 'เซาว์น่า', 'สระว่ายน้ำ', 'ลานจอด..."
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",6347000,2021.0,11.0,1,1,35.09,180.0,"['สระว่ายน้ำ', 'สวน', 'ระบบรักษาความปลอดภัย 24..."

In [17]:
data.facilities_list[1]

'[\'ระบบรักษาความปลอดภัย 24 ชม.</li></ul>\', \'<ul class="list-features"><li>ระบบรักษาความปลอดภัย 24 ชม.\']'

In [18]:
data.facilities_list[2]

"['ลานจอดรถในร่ม', 'เซาว์น่า', 'สระว่ายน้ำ', 'ฟิตเนส', 'สถานออกกำลังกาย', 'มินิมาร์ทใกล้เคียง', 'ห้องอบไอน้ำ', 'ลานจอดรถกลางแจ้ง', 'ระบบรักษาความปลอดภัย 24 ชม.', 'ศาลา']"

In [19]:
len(data.facilities_list[2][1:-1].split(", "))

10

In [20]:
facilities_list = []
for facilities in data['facilities_list']:
    if type(facilities) != float:
        facilities_list.append(len(facilities[1:-1].split(", ")))
    else:
        facilities_list.append(None)

facilities_list

[7,
 2,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 7,
 9,
 9,
 7,
 10,
 6,
 7,
 10,
 4,
 3,
 10,
 10,
 10,
 10,
 5,
 10,
 4,
 5,
 10,
 10,
 None,
 4,
 10,
 10,
 5,
 4,
 11,
 8,
 10,
 6,
 10,
 7,
 10,
 10,
 10,
 8,
 11,
 10,
 9,
 10,
 10,
 10,
 None,
 9,
 None,
 8,
 9,
 10,
 7,
 7,
 6,
 7,
 6,
 7,
 10,
 10,
 10,
 6,
 10,
 5,
 10,
 12,
 8,
 None,
 10,
 9,
 6,
 None,
 5,
 10,
 12,
 9,
 9,
 4,
 None,
 8,
 10,
 10,
 10,
 8,
 10,
 10,
 10,
 5,
 4,
 2,
 10,
 10,
 10,
 None,
 7,
 5,
 7,
 8,
 4,
 10,
 None,
 5,
 9,
 5,
 9,
 4,
 8,
 10,
 10,
 10,
 11,
 2,
 10,
 10,
 10,
 None,
 6,
 5,
 10,
 7,
 10,
 5,
 10,
 None,
 10,
 5,
 2,
 7,
 9,
 5,
 10,
 10,
 10,
 7,
 9,
 10,
 10,
 12,
 8,
 2,
 None,
 10,
 8,
 None,
 6,
 9,
 7,
 None,
 10,
 7,
 6,
 10,
 None,
 5,
 None,
 5,
 8,
 5,
 9,
 5,
 8,
 10,
 5,
 8,
 None,
 8,
 5,
 None,
 9,
 10,
 10,
 10,
 10,
 6,
 None,
 5,
 10,
 10,
 7,
 3,
 7,
 5,
 2,
 10,
 9,
 6,
 9,
 10,
 7,
 10,
 5,
 4,
 7,
 10,
 4,
 10,
 None,
 4,
 13,
 6,
 7,
 10,
 8,
 5,
 10,
 10,
 9,
 10,
 10,
 9,
 10,
 9,
 10,
 6,
 8,
 10,
 5,
 None,
 8,
 7,
 10,
 6,
 2,
 10,
 7,
 None,
 5,
 10,
 7,
 6,
 8,
 None,
 10,
 5,
 None,
 5,
 4,
 10,
 10,
 7,
 10,
 None,
 10,
 6,
 10,
 9,
 7,
 10,
 11,
 10,
 2,
 7,
 11,
 5,
 None,
 10,
 10,
 10,
 9,
 2,
 10,
 5,
 None,
 10,
 None,
 5,
 8,
 8,
 7,
 10,
 5,
 2,
 10,
 10,
 5,
 10,
 5,
 2,
 8,
 None,
 None,
 10,
 5,
 5,
 9,
 8,
 5,
 10,
 10,
 6,
 9,
 9,
 6,
 10,
 10,
 7,
 10,
 6,
 6,
 None,
 None,
 10,
 10,
 10,
 12,
 6,
 6,
 None,
 8,
 7,
 10,
 6,
 10,
 5,
 8,
 8,
 10,
 None,
 5,
 10,
 6,
 7,
 7,
 10,
 7,
 None,
 10,
 7,
 8,
 3,
 5,
 10,
 7,
 10,
 None,
 6,
 None,
 10,
 9,
 10,
 9,
 10,
 5,
 9,
 5,
 None,
 10,
 None,
 6,
 2,
 9,
 10,
 10,
 10,
 None,
 9,
 9,
 10,
 8,
 9,
 None,
 None,
 None,
 10,
 7,
 5,
 10,
 8,
 2,
 10,
 10,
 9,
 9,
 10,
 None,
 6,
 5,
 2,
 None,
 None,
 5,
 14,
 2,
 7,
 5,
 9,
 7,
 10,
 None,
 5,
 7,
 10,
 7,
 8,
 8,
 11,
 10,
 6,
 10,
 10,
 10,
 2,
 None,
 4,
 7,
 7,
 7,
 8,
 None,
 8,
 None,
 None,
 10,
 7,
 8,
 None,
 10,
 6,
 7,
 9,
 5,
 6,
 None,
 6,
 5,
 10,
 9,
 8,
 9,
 8,
 None,
 4,
 2,
 10,
 5,
 2,
 12,
 9,
 7,
 5,
 8,
 10,
 10,
 4,
 10,
 7,
 8,
 None,
 10,
 4,
 2,
 5,
 10,
 5,
 None,
 2,
 10,
 5,
 12,
 5,
 10,
 None,
 2,
 10,
 5,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 6,
 7,
 10,
 None,
 10,
 None,
 5,
 None,
 7,
 7,
 None,
 2,
 4,
 8,
 5,
 10,
 None,
 8,
 None,
 6,
 10,
 7,
 10,
 5,
 None,
 8,
 None,
 5,
 10,
 None,
 10,
 10,
 None,
 8,
 7,
 5,
 4,
 3,
 10,
 None,
 10,
 9,
 10,
 2,
 10,
 10,
 None,
 None,
 10,
 13,
 8,
 10,
 10,
 6,
 6,
 10,
 8,
 4,
 7,
 7,
 10,
 7,
 10,
 7,
 7,
 8,
 7,
 8,
 12,
 10,
 None,
 10,
 6,
 None,
 10,
 10,
 10,
 7,
 10,
 12,
 9,
 10,
 10,
 8,
 10,
 8,
 10,
 10,
 10,
 8,
 10,
 10,
 10,
 5,
 10,
 10,
 5,
 5,
 8,
 9,
 4,
 4,
 4,
 8,
 8,
 7,
 10,
 10,
 None,
 7,
 5,
 7,
 10,
 10,
 10,
 5,
 8,
 None,
 8,
 7,
 9,
 10,
 8,
 2,
 9,
 5,
 None,
 10,
 6,
 7,
 10,
 10,
 11,
 8,
 10,
 11,
 10,
 2,
 7,
 8,
 5,
 10,
 None,
 2,
 None,
 2,
 2,
 4,
 None,
 10,
 9,
 6,
 8,
 5,
 6,
 5,
 9,
 5,
 10,
 4,
 2,
 6,
 11,
 7,
 10,
 None,
 5,
 8,
 8,
 10,
 None,
 None,
 6,
 9,
 None,
 None,
 None,
 7,
 2,
 10,
 10,
 7,
 7,
 9,
 8,
 10,
 10,
 8,
 10,
 8,
 8,
 10,
 10,
 None,
 9,
 10,
 10,
 None,
 12,
 4,
 9,
 None,
 None,
 8,
 5,
 12,
 11,
 4,
 2,
 None,
 10,
 10,
 10,
 8,
 8,
 9,
 7,
 5,
 10,
 12,
 10,
 10,
 3,
 8,
 4,
 10,
 10,
 None,
 None,
 10,
 2,
 10,
 6,
 6,
 9,
 10,
 7,
 8,
 10,
 10,
 8,
 7,
 10,
 7,
 7,
 5,
 7,
 7,
 10,
 3,
 5,
 10,
 10,
 7,
 10,
 10,
 5,
 6,
 7,
 6,
 8,
 2,
 6,
 7,
 6,
 7,
 5,
 7,
 10,
 8,
 6,
 10,
 8,
 10,
 10,
 10,
 10,
 6,
 7,
 5,
 10,
 6,
 6,
 5,
 10,
 8,
 10,
 10,
 10,
 10,
 10,
 8,
 10,
 7,
 10,
 10,
 9,
 5,
 7,
 10,
 2,
 10,
 5,
 10,
 4,
 8,
 10,
 7,
 10,
 5,
 10,
 9,
 10,
 10,
 9,
 2,
 6,
 10,
 5,
 9,
 10,
 10,
 10,
 10,
 6,
 8,
 5,
 None,
 8,
 9,
 7,
 6,
 10,
 10,
 7,
 6,
 4,
 None,
 10,
 7,
 7,
 10,
 7,
 10,
 4,
 None,
 10,
 10,
 10,
 5,
 4,
 9,
 5,
 4,
 7,
 2,
 11,
 None,
 7,
 10,
 6,
 6,
 4,
 6,
 6,
 9,
 10,
 7,
 6,
 10,
 10,
 4,
 None,
 9,
 8,
 6,
 8,
 None,
 7,
 7,
 10,
 10,
 5,
 2,
 8,
 5,
 None,
 8,
 8,
 8,
 3,
 10,
 10,
 4,
 8,
 5,
 8,
 None,
 7,
 8,
 10,
 None,
 7,
 10,
 7,
 10,
 2,
 2,
 10,
 8,
 5,
 5,
 7,
 8,
 10,
 9,
 10,
 10,
 9,
 10,
 7,
 7,
 None,
 10,
 8,
 9,
 6,
 10,
 8,
 10,
 7,
 9,
 5,
 6,
 2,
 10,
 6,
 2,
 4,
 8,
 6,
 5,
 6,
 2,
 10,
 7,
 10,
 8,
 7,
 5,
 None,
 7,
 10,
 8,
 10,
 12,
 7,
 10,
 12,
 10,
 9,
 6,
 9,
 2,
 7,
 4,
 10,
 5,
 10,
 8,
 7,
 9,
 6,
 4,
 6,
 10,
 10,
 10,
 12,
 7,
 6,
 7,
 10,
 9,
 8,
 6,
 8,
 8,
 10,
 2,
 2,
 10,
 3,
 6,
 7,
 None,
 6,
 9,
 10,
 10,
 8,
 5,
 10,
 10,
 10,
 10,
 10,
 None,
 None,
 10,
 10,
 None,
 7,
 10,
 9,
 8,
 7,
 8,
 10,
 2,
 7,
 2,
 6,
 ...]

In [21]:
data['facilities_list'] = facilities_list
data.head()

,name_list,Province,Sub_Area,location_list,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",3140000,2019.0,32.0,1,1,23.53,450.0,7.0
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,"สามเสนนอก, กรุงเทพ",5850000,NaN,8.0,1,1,66.00,960.0,2.0
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,"สุขุมวิท, กรุงเทพ",14500000,2021.0,30.0,2,2,51.66,1070.0,10.0
3,อนิล สาทร 12,กรุงเทพ,สีลม,"สีลม, กรุงเทพ",15000000,2022.0,15.0,1,1,45.77,490.0,10.0
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,"จอมพล, กรุงเทพ",6347000,2021.0,11.0,1,1,35.09,180.0,10.0

In [22]:
data.drop('location_list', axis=1, inplace=True)
data.head()

,name_list,Province,Sub_Area,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,เดนิม จตุจักร,กรุงเทพ,จอมพล,3140000,2019.0,32.0,1,1,23.53,450.0,7.0
1,คอนโด Samran Mansion 1 นอน ห้องใหญ่ ใกล้ MRT ห...,กรุงเทพ,สามเสนนอก,5850000,NaN,8.0,1,1,66.00,960.0,2.0
2,พาร์ค ออริจิ้น ทองหล่อ,กรุงเทพ,สุขุมวิท,14500000,2021.0,30.0,2,2,51.66,1070.0,10.0
3,อนิล สาทร 12,กรุงเทพ,สีลม,15000000,2022.0,15.0,1,1,45.77,490.0,10.0
4,ไลฟ์ ลาดพร้าว แวลลีย์,กรุงเทพ,จอมพล,6347000,2021.0,11.0,1,1,35.09,180.0,10.0

In [23]:
data.drop('name_list', axis=1, inplace=True)
data.head()

,Province,Sub_Area,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,กรุงเทพ,จอมพล,3140000,2019.0,32.0,1,1,23.53,450.0,7.0
1,กรุงเทพ,สามเสนนอก,5850000,NaN,8.0,1,1,66.00,960.0,2.0
2,กรุงเทพ,สุขุมวิท,14500000,2021.0,30.0,2,2,51.66,1070.0,10.0
3,กรุงเทพ,สีลม,15000000,2022.0,15.0,1,1,45.77,490.0,10.0
4,กรุงเทพ,จอมพล,6347000,2021.0,11.0,1,1,35.09,180.0,10.0

In [24]:
data = data[data['Province'] == 'กรุงเทพ']
len(data)
data.drop('Province', axis=1, inplace=True)
data.head()

,Sub_Area,price_list,built_year_list,floor_list,bedroom_list,bathroom_list,area_list,distance_to_transport_list,facilities_list
0,จอมพล,3140000,2019.0,32.0,1,1,23.53,450.0,7.0
1,สามเสนนอก,5850000,NaN,8.0,1,1,66.00,960.0,2.0
2,สุขุมวิท,14500000,2021.0,30.0,2,2,51.66,1070.0,10.0
3,สีลม,15000000,2022.0,15.0,1,1,45.77,490.0,10.0
4,จอมพล,6347000,2021.0,11.0,1,1,35.09,180.0,10.0

In [25]:
data = data.dropna()

In [26]:
len(data)

2034

In [27]:
data.to_csv('cleaned_data.csv', index=False)